### ISSUE TITLE
no permissions in etc/suddoers.d

### ISSUE THREAD

**Issue by saikoispro** [Apricity-OS/apricity-build#106]
Hello, I've had a problem with the terminal, I installed this os about a week ago, and I can't fix this problem, I've been searching information about how to fix it, but I couldn't, I came here to ask for help. if you can do something, thanks for helping me

**Comment by agajews** [comment]
What exactly are you trying to do? `/etc/sudoers.d` is explicitly not readable or writeable by users, only by root.

**Comment by agucova** [comment]
This issue should be closed as there hasn't been a response in 43 days, and the issue wasn't totally described.
