### ISSUE TITLE
Services fail to start on boot

### ISSUE THREAD

**Issue by dealloc** [Apricity-OS/apricity-build#122]
I recently installed the latest version coming from the beta version,
The first thing I noticed is that my boot is many times slower due 3 services failing to start on boot.
The first one is dhcpd which on itself sometimes takes 30 seconds before it fails and then suggests me to take a look in the systemd log files for more info, so here they are:

```
 dealloc  ~  sudo systemctl status dhcpcd@enp1s0.service
[sudo] password for dealloc: 
● dhcpcd@enp1s0.service - dhcpcd on enp1s0
   Loaded: loaded (/usr/lib/systemd/system/dhcpcd@.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-08-31 10:31:06 CEST; 15min ago
  Process: 405 ExecStart=/usr/bin/dhcpcd -q -w %I (code=exited, status=1/FAILURE)

Aug 31 10:30:36 Abstergo systemd[1]: Starting dhcpcd on enp1s0...
Aug 31 10:30:36 Abstergo dhcpcd[405]: enp1s0: waiting for carrier
Aug 31 10:30:37 Abstergo dhcpcd[405]: wlp2s0: new hardware address: 02:8c:ef:ef:e6:c0
Aug 31 10:30:38 Abstergo dhcpcd[405]: wlp2s0: new hardware address: d0:53:49:5d:a3:83
Aug 31 10:31:06 Abstergo systemd[1]: dhcpcd@enp1s0.service: Control process exited, code=exited status=1
Aug 31 10:31:06 Abstergo systemd[1]: Failed to start dhcpcd on enp1s0.
Aug 31 10:31:06 Abstergo systemd[1]: dhcpcd@enp1s0.service: Unit entered failed state.
Aug 31 10:31:06 Abstergo systemd[1]: dhcpcd@enp1s0.service: Failed with result 'exit-code'.
```

The second service I saw failing was NetBIOS and the Samba SMB service, which each can take up to 20-30 seconds each before failing as well, again; systemd logs below:

```
 dealloc  ~  sudo systemctl status smbd
● smbd.service - Samba SMB/CIFS server
   Loaded: loaded (/usr/lib/systemd/system/smbd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-08-31 10:31:06 CEST; 18min ago
  Process: 3494 ExecStart=/usr/bin/smbd -D (code=exited, status=1/FAILURE)

Aug 31 10:31:06 Abstergo systemd[1]: Starting Samba SMB/CIFS server...
Aug 31 10:31:06 Abstergo systemd[1]: smbd.service: Control process exited, code=exited status=1
Aug 31 10:31:06 Abstergo systemd[1]: Failed to start Samba SMB/CIFS server.
Aug 31 10:31:06 Abstergo systemd[1]: smbd.service: Unit entered failed state.
Aug 31 10:31:06 Abstergo systemd[1]: smbd.service: Failed with result 'exit-code'.
 dealloc  ~  sudo systemctl status nmbd.service                                                                 3 
● nmbd.service - Samba NetBIOS name server
   Loaded: loaded (/usr/lib/systemd/system/nmbd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-08-31 10:31:06 CEST; 18min ago
  Process: 3480 ExecStart=/usr/bin/nmbd -D (code=exited, status=1/FAILURE)

Aug 31 10:31:06 Abstergo systemd[1]: Starting Samba NetBIOS name server...
Aug 31 10:31:06 Abstergo systemd[1]: nmbd.service: Control process exited, code=exited status=1
Aug 31 10:31:06 Abstergo systemd[1]: Failed to start Samba NetBIOS name server.
Aug 31 10:31:06 Abstergo systemd[1]: nmbd.service: Unit entered failed state.
Aug 31 10:31:06 Abstergo systemd[1]: nmbd.service: Failed with result 'exit-code'.
```

This makes for almost an entire minute of boot time that's wasted on services that simply fail and thus do nothing. I don't experience any problems with my internet however (the problem I had in beta; that my WiFi would randomly disconnect is even solved with the stable release thanks!) and if I check if those services are enabled (so I could disable them on boot) they claim to be disabled.

Any ideas on how to fix these services (or just right out disable them)? Because Windows starts in like 5 seconds and Apricity takes over one minute and a half because of this

**Comment by dealloc** [comment]
I'm currently doing a workaround by masking the dhcpd@enp1s0 service, I haven't tested how this plays with ethernet connections yet, but I'm suspecting I just disabled that functionality alltogether..
It was hell to get systemd not to load that DHCP service though, I had to mask to kill it

**Comment by agajews** [comment]
You should be able to disable smbd and nmbd without any side-effects. Dhcpcd has been acting strange everywhere; I'll have to look into it a bit more.

**Comment by dealloc** [comment]
I indeed managed to disable smbd and nmbd, I masked dhcpd using `systemctl mask dhcpd@enp1s0` and have been running for almost a week now without any side effects. it's odd though, it's never explicitly enabled for as far as I could tell in Systemd however masking it does somehow disable it; indicating that systemd somewhere does in fact start the service (maybe as a dependency?)

**Comment by vamartid** [comment]
I have the same problem but on me if I mask dhcpcd@enp1s0.service my gnome session does not start after entering the password on gdm,I just throw me on gdm again.

**Comment by NickCis** [comment]
In my case _samba_ was failing to start because there was no configuration file. Apricity installed `/etc/samba/smb.conf.default` but the file `/etc/samba/smb.conf` didn't exist.

I created the configuration file copying the default one and _samba_ service started correctly:

```
# cp /etc/samba/smb.conf.default /etc/samba/smb.conf
# systemctl restart smbd
```

**Comment by dealloc** [comment]
@vamartid that doesn't seem to make sense to me, why would masking a network service interfere with your GDM

**Comment by vamartid** [comment]
Even if I mask it without disabling the other two services dealloc did gdm still does not let me in my user account.I recently tried to log in as root and it was possible. Maybe something with the privileges.

**Comment by vamartid** [comment]
I recently retried masking the service and it worked fine.
I do not know if anything I recently did had anything to do with that(any update or anything).
I did though reinstalled gdm but only to fix an other not relevant prob I had with a recent update, but I can not say if it is relevant with the fact I could perform the mask and be able to login to my user account.
Anyway this works for now.  :+1:

**Comment by atar-axis** [comment]
can confirm both errors and both workarounds/solutions (cp the smbd file and masking the dhcp service)
