### ISSUE TITLE
Hi-DPI display flickering

### ISSUE THREAD

**Issue by habutre** [Apricity-OS/apricity-build#125]
Hi all!

Sometime ago I share [here](https://github.com/Apricity-OS/apricity-build/issues/89) the same issue and I was hoping some updates solve my problem, but not.

I'm totaly stuck on trying to figure out how to fix (definitely) this issue. Looking on `xorg.log` and `journalctl -xef` nothing seems to tell me what is going on or any smell about what could be the debug start point.

Suddenly my hi-dpi lcd starts to flicking, but not like when we have a frequency misconfigured, is something like trying to keep the scaling factor or when the Xorg -configure tries to find out the right monitor/video configuration.

Might anyone help me to find the right way to start this debugging?

My hardware config is:

> Monitor resolution: 3200x1800QHD+ 276PPI
> Intel HD Graphics 4400
> 12.7 in

**Comment by agajews** [comment]
What kind of laptop is it?

**Comment by habutre** [comment]
Asus Zenbook ux303ln
Intel Corporation HD Graphics 5500 (rev 09) < - - my mistake on previous description
Dimensions:    3200x1800 pixels (846x476 millimeters)


*boot options*
```
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-linux root=UUID=961fe3ca-12c3-4046-bc30-dbfa4464aacc rw quiet splash acpi_osi= resume=UUID=
```

**Comment by habutre** [comment]
I have not found a solution yet, but some tips are throwing up on each trying.

I realized which moving mouse throught the trackpad the flickering stops, releasing the pad the flickering goes back.

If anyone have any info about this or even if here is not the right place to go in order to solve this issue, feel free to comment.

**Comment by habutre** [comment]
After latest full upgrade the flickering stops, even using scale 1 or 2.
Great!

What was changed? I have no idea, but now works, stuffs that the time will resolve.
