### ISSUE TITLE
Add the ability to modify base.toml for freezedry configuration

### ISSUE THREAD

**Issue by Limero** [Apricity-OS/apricity-build#129]
As an advance user, it would be great to get the option to modify what packages from base.toml are included in a freezedry configuration. That way, you could disable packages like printer drivers and Wi-Fi related things if you wanted to slim down your install.

Another option would be to add the ability to completely ignore base.toml and let the user manually specify all wanted things in the regular packages section on a freezedry configuration.

**Comment by agajews** [comment]
I'm moving this to the freezedry repo. The simplest solution would be to make a minimal `core.toml` config that contains base, base-devel, freezedry, and freezedry's immediate dependencies.

**Comment by rjslinux** [comment]
Unsubscribe me please

**Comment by agajews** [comment]
@rjslinux to unsubscribe click the unsubscribe link at the bottom of the email.
