### ISSUE TITLE
pathogen and kalisi are missing after installation

### ISSUE THREAD

**Issue by ejelome** [Apricity-OS/apricity-build#130]
Hi, new ApricityOS user here, not sure if this is only on my part, please close this ticket if it is, but this is a bug fix (if you call it that).

So after the installation and full update (some 230+ package updates), I did try doing some scripting in Vim and constantly encountered this `pathogen` (missing function) and `kalisi` (missing color scheme), it seems that they are not installed properly (looks like they're not in the vim directory at all), so got it fixing by simply putting them on their proper places (straight from the github page instructions of `pathogen` and `kalisi`):

For `pathogen`:

```
$ curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim --create-dirs
```

For `kalisi`:

```
$ git clone https://github.com/freeo/vim-kalisi ~/.vim/bundle/vim-kalisi
```

... and that solved the problem.

**Comment by dealloc** [comment]
Since this is actually quite an easy fix I'm gonna see about creating a PR for this

**Comment by ghost** [comment]
This is still not solved :)

**Comment by ghost** [comment]
Since apricityos have bid farewell, I'd clsoe this issue :(
