### ISSUE TITLE
Apricity OS installer bug

### ISSUE THREAD

**Issue by prabhakar97** [Apricity-OS/apricity-build#136]
Situation
-------------------------------
Wanted to Install the OS on a block device attached at /dev/sdc on the live system.
Selected erase entire disk and chose /dev/sdc's MBR as the target device for bootloader installation.
Entered desired username and password and went ahead.

What was expected?
---------------------------
The installation summary should have showed /dev/sdc's MBR as bootloader installation target. 

What happened actually?
----------------------------------
The installation summary showed me that the bootloader will be installed on /dev/sda.

Repeated a couple of times and it behaved in the same way. Then I chose to partiation manually. Created an EXT4 and a SWAP on /dev/sdc and chose its MBR as bootloader target. This time the installation summary showed correct device as bootloader target.

**Comment by RubenKelevra** [comment]
I think you should create this bug under the installer-repo:

https://github.com/Apricity-OS/calamares

**Comment by prabhakar97** [comment]
Thank you! I am closing it here and creating in calamares repo.
