### ISSUE TITLE
NVidia driver crashes system

### ISSUE THREAD

**Issue by drumstasd** [Apricity-OS/apricity-build#141]
I installed packages for my nvidia card (nvidia, nvidia-libgl, nvidia-settings), and they seemed to crash the system. Everything I got to see was the picture below. Any ideas or suggestions?

![20161011_100728](https://cloud.githubusercontent.com/assets/17199717/19261693/91335dde-8f9b-11e6-98e8-236aca8baa69.jpg)

**Comment by agajews** [comment]
What kind of an nvidia graphics card do you have? It could be a specific model that isn't supported by the broader nvidia and nvidia-libgl packages.

**Comment by Mufyn** [comment]
I have a Geforce GT840M
