### ISSUE TITLE
Teamviewer can't connect

### ISSUE THREAD

**Issue by Typhon0** [Apricity-OS/apricity-build#146]
Since the last update teamviewer can't connect to the server.
![teamviewer](https://cloud.githubusercontent.com/assets/10800948/19455812/dddbd6c0-94be-11e6-806b-c97dc27fbdba.png)

**Comment by Mr-Smithy-x** [comment]
I'm having this issue as well
![screenshot from 2016-10-19 21-05-15](https://cloud.githubusercontent.com/assets/9755159/19542815/cc73e6f2-963f-11e6-9940-b7c6395db2a4.png)

**Comment by Typhon0** [comment]
Same problems  reported on the [AUR](https://aur.archlinux.org/packages/teamviewer)

**Comment by agajews** [comment]
I'm going to close this issue because Apricity doesn't maintain the Arch package of TeamViewer. Feel free to reopen it if you have any other questions.
