### ISSUE TITLE
Software manager not responding !!!!

### ISSUE THREAD

**Issue by Lauel09** [Apricity-OS/apricity-build#147]
# ## When i gone to start software manager it was not responding for next 3 minutes then after 3 minutes

it was showing all the software ,i was thinking it will be other problem but when i tried to install any software,there was a message this is a corrupt database.

**Comment by shemux** [comment]
try the following command to remove pacman's corrupted database:
`rm /var/lib/pacman/db.lck`
if you want to update all packages, try in prompt:
`sudo su pacman -Syu`
