### ISSUE TITLE
Apricity OS DOESN'T WORK AT ALL

### ISSUE THREAD

**Issue by Robostatic** [Apricity-OS/apricity-build#151]
Hi

I am new to Apricity, yet I have installed numerous operating systems, including Windows 7, 8.1, and 10; Ubuntu, Xubuntu, Kubuntu, Peppermint, Manjaro, Zorin, elementaryOS, and LXLE.

Unfortunately, Apricity OS hates me and it doesn't allow me to boot, showing only this menu

![capture](https://cloud.githubusercontent.com/assets/23415341/20236789/67b75cc2-a8d1-11e6-848a-d6221c8c9d08.PNG)

I have no OS, as this is in VMware, and I will try it on a real computer, but I would like to get to the bottom of it.

Please help me! I have searched for 5 hours looking for any answer but got none. Help me!

**Comment by habutre** [comment]
@Robostatic I really don't get what step you are. You have mentioned VMWare and real computer.
I've faced some issues during installation specially on boot partitioning, bootloader and installation finishing.

Could you explain better what step you are on apricity installation? If you not give  up at all.

**Comment by Robostatic** [comment]
Thanks. I figured it out and the reason was because the computer had an i686 CPU, not an x86_64

**Comment by habutre** [comment]
Great! So might you close this issue once it was solved. :+1:
