### ISSUE TITLE
Installer stucks on bootloader setup at 94%

### ISSUE THREAD

**Issue by habutre** [Apricity-OS/apricity-build#152]
I'd used the latest `ApricityOS` release `09.2016` to reinstall my entire system after it became unusasable when I upgraded my kernel from `4.8.6-1` to `4.8.7-1` (I have no idea why!)

But after follow all steps to install the installer stucks on 94% setting up the bootloader. Three tries later I decide to restart on that point, guessing all needed operations had been done.

And guess what? All works fine, but I waste hours trying to understand what I'd made wrong while the installation process had already finished.

**Comment by JeffersonTeixeira** [comment]
Try to install without Internet Connection. Also if u are using Windows and need an USB bootable drive, try to create it with USB WRITE [https://sourceforge.net/projects/usbwriter/](url)

**Comment by habutre** [comment]
Hi @JeffersonTeixeira I were able to finalize the installation. The problem here is the installer never ends. I just reboot the system and worked fine, so the issue seems to be the installer detects the final installation, can be a internet connection as you said, but might not end up like this - this is the point.

BTW, I've been using linux from several years yet, but newbies will find this kind of issues a excuse to not try it.

**Comment by habutre** [comment]
ApricityOS is dead, no make sense keep this issue opened.
