### ISSUE TITLE
Hangs up while opening many applications

### ISSUE THREAD

**Issue by satish-zol** [Apricity-OS/apricity-build#25]
Hi there,

I am using apricity from last two months and I love it. Sometimes getting hang my system while opening many applications, I am using 8GB RAM, intel I3 processor. I cross checked the available RAM from another session and it seems the RAM is enough available, still my desktop environment is getting hang and after sometime or reboot it works normal. Please take a look into issue and suggest a best way to overcome this issue.

Thanks

**Comment by gogobebe2** [comment]
Well, you do have an i3... :laughing:. I wouldn't know how to overcome this other than buying a better cpu.

**Comment by rjslinux** [comment]
The CPU is not the problem he is having - my home server is running the
same CPU with no issues.

From what I found it is the Adwaita cursor theme - long time problem in
Arch BBS <https://bbs.archlinux.org/viewtopic.php?id=197383>.

I downloaded another cursor theme and set it as the default and the problem
is next to none existant (depending how many apps I have open at the same
time). Basically for normal use, no hanging issues yet. I changed the
cursor theme over two weeks ago and very rarely have the hanging issue
anymore.

**Comment by gogobebe2** [comment]
I've never had this issue with 8GB ram and i7 CPU.
From what you say, the problem is most likely the Adwaita cursor theme needing better harder to work properly effectively.
> The CPU is not the problem he is having
So yes, it is. But it also isn't.
