### ISSUE TITLE
Distribute packages safely

### ISSUE THREAD

**Issue by embik** [Apricity-OS/apricity-build#54]
Someone on HackerNews [pointed out](https://news.ycombinator.com/item?id=11420627) ApricityOS distributes its packages via plaintext HTTP and skips any form of signature checks. [The repository in question](https://github.com/agajews/ApricityOS/blob/master/build/pacmanx86_64.conf#L75).

````
[apricity-core]
SigLevel = Never
Server = http://apricityos.com/apricity-core/
```

This should be fixed as it allows unknown parties to man-in-the-middle traffic between ApricityOS and its repositories and to plant malicious packages with relatively low effort.

**Comment by stuffandthings** [comment]
I'd be willing to help out with this issue.

**Comment by embik** [comment]
Looks like this [has been fixed](https://github.com/Apricity-OS/apricity-build/blob/master/airootfs-all/etc/pacman.conf). I appreciate @agajews listened to feedback although I'd wish this had been communicated here. Proper issue tracking and handling helps building trust, especially when it's related to security sensitive topics.

Nonetheless, this is resolved and can obviously be closed. Good luck to the people working on Apricity.
