### ISSUE TITLE
apricity-themes-gnome doesn't upgrade

### ISSUE THREAD

**Issue by luvemil** [Apricity-OS/apricity-build#61]
My Gnome got broken. The panel on the bottom on the screen doesn't load and the icons don't have the correct size, like in issue #57. I tried

```
sudo pacman -Qqi apricityassets apricity-themes-gnome
```

and got

```
Name            : apricityassets
Version         : 0.2.4-1
...
Name            : apricity-themes-gnome
Version         : 0.1.9-1
```

The first is ok, but `apricity-themes-gnome` should be 1.0.0-1 according to #57 again. However `pacman -Syu` and the graphic installer both say that the system is up to date.

UPDATE: I manually installed `apricity-themes-gnome` to the latest version, and now the icons are not broken anymore. The bottom bar is still missing and pacman is still convinced that the latest version of `apricity-themes-gnome` is 0.1.9-1, so maybe the issue is with pacman.

UPDATE2: Digging into `gnome-tweak-tool` configurations I realized that the dock wans't working because `dash-to-dock` had some errors, so I manually installed it and now it works properly. Pacman still won't upgrade `apricity-themes-gnome`.

**Comment by agajews** [comment]
The fix is being uploaded as we speak.

**Comment by luvemil** [comment]
Awesome. It works now!
