### ISSUE TITLE
Scrolling on touchpad

### ISSUE THREAD

**Issue by dvorapa** [Apricity-OS/apricity-build#78]
Some touchpads has got an area on the right (and bottom sometimes) to scroll with one finger (and their owners are used to use this instead of two fingers gesture). Ubuntu or Debian have got this setting. Could you add it too?

**Comment by danipozodg** [comment]
As far as I know, it has to do with the input library being used in Apricity. The default is xf86-input-synaptics, which doesn't have as much functionality as libinput, used by other systems. From my own investigations in the GNOME IRC channel, the maintainer of both seems to be the same person, who dedicates more time to libinput. You can try to switch to libinput and see if it works for you. Alternatively, you might enter `synclient VertEdgeScroll=1` in a shell to get that functionality during that session.

**Comment by dvorapa** [comment]
I'll try and we'll see

**Comment by dvorapa** [comment]
I have got both preinstalled on Apricity, but shell says `Couldn't find synaptics properties. No synaptics driver loaded?`

**Comment by dvorapa** [comment]
Libinput didn't help

**Comment by habutre** [comment]
In my turn, I try to move entirely to libinput and got a huge headache.

Using only libinput, my screen got locked/frozen until click with mouse/touchpad, and follows like that between keyboard and mouse events. A complete mess, so I back to limited synaptics and now also without my finger-tap. 

Always when I run Apricity from liveusb all seems to work perfectly, but the rolling updates time by time were bringing me back to the other distros headaches, almost unable to handle my Zenbook UX305 hardware. Its not only a criticize, but Apricity firstly give me hope that  I was finally found a distro to deal with my machine; anyway I'm thanks and hope to found a solution and also I'm here to help to found the solutions I only need a path to .

**Comment by Geovo** [comment]
Had the same issue on my Macbook Pro 10,1. I was able to configure the trackpad with synclient, but it's not the "right" way to do it. So I just reinstalled xf86-input-libinput, moved the
`/etc/X11/xorg.conf.d/70-synaptics.conf`
file to my Desktop (to keep it in case anything goes wrong) and created a new file:
`/etc/X11/xorg.conf.d/60-libinput.conf`
with these contents:
[https://github.com/whot/xf86-input-libinput/blob/master/conf/60-libinput.conf](https://github.com/whot/xf86-input-libinput/blob/master/conf/60-libinput.conf)
After that just logout and login again (no need to reboot). You should also see the Mouse Settings come back.
Let me know if this was helpful. Cheers!

**Comment by habutre** [comment]
The @Geovo tip at least help me to bring back the middle-click paste (what freedom!)

**Comment by dvorapa** [comment]
Fixed upstream (included as a preference in Gnome)
