### ISSUE TITLE
Dock should indicate there are more windows of the same app openned by default

### ISSUE THREAD

**Issue by dvorapa** [Apricity-OS/apricity-build#79]

**Comment by itsgg** [comment]
@dvorapa Do you have any suggestion? Mac OSX dock doesn't visually indicate multiple windows.

**Comment by dvorapa** [comment]
There actually is Gnome standard bullet notation in tweak tools, so something similar for lines in Apricity design would be ok. half lines? hamburger?

**Comment by dvorapa** [comment]
Reported upstream (https://github.com/micheleg/dash-to-dock/issues/697)
