### ISSUE TITLE
No more UPDATES?

### ISSUE THREAD

**Issue by laloalire** [Apricity-OS/apricity-build#89]
i have an issue with the update manager, it says "Unexpected error" Failed to sync with the database

**Comment by agajews** [comment]
Should be fixed now.

**Comment by danipozodg** [comment]
I'm getting the same error since June 4th, and as of now it doesn't seem to be fixed.

**Comment by agajews** [comment]
What branch of the OS are you on?

**Comment by laloalire** [comment]
It isn't fixed.. 
How i see what branch of the OS am i on?

**Comment by agajews** [comment]
Which one did you download from the site?

**Comment by laloalire** [comment]
apricity_os-gnome-03.2016-beta

**Comment by habutre** [comment]
I've been updating my system every day, also yesterday my ZenBook Hi-Dpi start to flicking due an arrived xorg-* update.

**Comment by ferbraz89** [comment]
Updates are working for me too.

**Comment by itsgg** [comment]
Updates are working fine for the both editions in multiple machines I checked. Can this be closed? @agajews @laloalire

**Comment by agajews** [comment]
@laloalire I'm closing this issue. If you're still having trouble, feel free to reopen it.
