### ISSUE TITLE
Terminal home and end keys do not work

### ISSUE THREAD

**Issue by tommyshem** [Apricity-OS/apricity-build#91]
In  the terminal with zsh the end key and home key do not work.

Type in bash to change to bash and the end and home keys work so it most be a config file problem somewhere.

New to zsh so can not find in config files how to change.

Google search this problem and in terminal type in
cat
and press the home key, the press ctrl and c to exit and the key code is printed in the terminal.
This is then used to bind the key code to the actions in zsh some how.

If install the grml-zsh-config from pamac in the extras the end and home keys work but the colour arrow bars disappear. Works but does not look as good.

Like the distro so far. Moved from Mint Linux to Arch but Arch to hard to setup with only basic skills. Needed an arch distro which could be installed offline and then updated and setup changes my self later. I had a look at Antergos but it install's online which is no good for me as no network connection where I want to install it.
I have looked at Manjaro which is nice but it keeps on acting up on the graphics side as I must have a problem graphics card. As could not boot the live cd on my computer but worked on another computer.
Problems installing your distro on my computer and seams to be working ok.
 I have mainly used the Mate and cinnamon but I have gone for gnome3 for a change. Used the extensioins to make it work like mate and cinnamon as I like the menu at the top.

If you need any more info or need me to try out th fix if you find one, then let me know.

**Comment by agajews** [comment]
Add these two lines to your .zshrc (I'll add them to the OS later this month)

`bindkey "${terminfo[khome]}" beginning-of-line`
`bindkey "${terminfo[kend]}" end-of-line`

**Comment by tommyshem** [comment]
I have tested with this and it does not work on my computer. 
The key bindings are different to the xterm-256-color file.
My computer uses [[H for home
and end is [[F
also noticed that when you press delete key the ~ is displayed instead.
Does this work on your computer. My locale settings are set to united kingdom not sure if this helps.

**Comment by habutre** [comment]
Hey maybe it can help https://wiki.archlinux.org/index.php/Home_and_End_keys_not_working
In my zenbook these keys are also ^[[H and ^[[F, this wiki helps to configure and recompile the terminfo

**Comment by tommyshem** [comment]
**Thank you for the info.** 
_I have looked at that and it looks like to many steps for me._

**I have found this below and it works ok.**
Just add this to your ~/.zshrc file.
Also found this when looking in to this problem the top part is for autocompletion with arrow key interface, which I like.

**Below is from my ~/.zshrc file.**

```
# **** Get autocomplete with arrow-key driven interface (Press tab twice) ********
zstyle ':completion:*' menu select

#  ******** Get keys working *****************************************************
case $TERM in
	xterm*) 
	bindkey "^[[H" beginning-of-line	            # Home (xterm)
	bindkey "^[[F" end-of-line			    # End (xterm)
	bindkey "\e[3~" delete-char                         # Delete
	bindkey '^[[5~'  history-beginning-search-backward  # Page Up
	bindkey '^[[6~'  history-beginning-search-forward   # Page Down
	bindkey '^[[2~' overwrite-mode                      # Insert
;;
esac
```

Thank you for the feed back.

**Comment by dvorapa** [comment]
@agajews please don't forget

**Comment by agajews** [comment]
Yes, I'll make sure it's added to the June releases.

**Comment by dvorapa** [comment]
:+1:
