### ISSUE TITLE
Tap-to-click stopped working

### ISSUE THREAD

**Issue by dvorapa** [Apricity-OS/apricity-build#93]
Today after update tap-to-click option stopped working completely. It also disappeared from settings (or tweaks?)

**Comment by CBR09** [comment]
Same issue, after update system, I can't use touchpad to click anymore.

**Comment by agajews** [comment]
Caution, this may break things.

Gnome has recently switched over to libinput. You can try removing the packages `xf86-input-evdev` and `xf86-input-synaptics` from your system and making sure that `libinput` is installed. Also, when you log in from GDM, check to see which version of Gnome (Wayland or regular X) you're using by hitting the gear cog below your username.

**Comment by dvorapa** [comment]
That solved it, thank you

**Comment by dealloc** [comment]
The temporary fix I'm currently using is running this in the console
``` synclient TapButton1=1 TapButton2=3 TapButton3=2 ```
putting that in the startup fixes the system

(Running Gnome 3.20.2)

**Comment by CBR09** [comment]
Thanks @dealloc , it work for me

**Comment by dealloc** [comment]
@CBR09 note that this is a quickfix, you should consider using the more permanent solution proposed by @agajews

**Comment by agajews** [comment]
I'm going to close this issue. Feel free to reopen it if you have more problems.

**Comment by mdPlusPlus** [comment]
Thank you, @agajews, replacing `xf86-input-evdev` and `xf86-input-synaptics` with `xf86-input-libinput` worked!

**Comment by dvorapa** [comment]
@agajews it works without problem, but could you remove `xf86-input-synaptics` from installation?

**Comment by agajews** [comment]
I'll make sure it's removed in the June releases.

**Comment by dvorapa** [comment]
:+1:

**Comment by habutre** [comment]
@agajews  I tried the instruction on [comment 93](https://github.com/Apricity-OS/apricity-build/issues/93#issuecomment-226376700) but I got in trouble.
I installed `libinput` and `xf86-input-libinput` but when I remove `xf86-input-synaptics` all stopped working: keyborad + mouse/touchpad. The only thing I didn't remove was `xf86-input-evdev`, could it be my failure-cause?

**Comment by dealloc** [comment]
@habutre have you tried my solution for a (temporary) fix? I read on some fora the problem might be related to the devices not being properly recognized at boot time and thus not being properly initialized (which is what my suggestion does)

**Comment by habutre** [comment]
@dealloc I tried and the workaround works, the tap events were captured but I will wait for a definitive solution mainly because before that change my tap configuration was capturing 1, 2 and 3 fingers taps, pasting from gpm2 protocol, etc. Anyway thanks for your help

**Comment by pedrojioc** [comment]
@dvorapa 
Could you help me,
As you did to solve the problem .
I am new to linux, and I spend this problem after updating .

I appreciate if you could explain. ( Sorry for my English )
Thank you

**Comment by dvorapa** [comment]
@pedrojioc Try this: install `libinput` from pamac (add/remove software in app menu), then uninstall `xf86-input-synaptics` and restart. Beware! Always have an external mouse nearby if you'll need it.

**Comment by pedrojioc** [comment]
@dvorapa Thank you very much , with your help achieve solve the problem.

**Comment by dealloc** [comment]
Removing `xf86-input-synaptics` for some reason marked all my packages as orphans, odd and dangerous
