### ISSUE TITLE
Default Email client

### ISSUE THREAD

**Issue by itsgg** [Apricity-OS/apricity-build#97]
Can we include Geary as the default email client?

**Comment by agajews** [comment]
We're debating between Geary and Nylas N1. Anybody have a strong opinion?

**Comment by itsgg** [comment]
In my opion Epiphany for browser and Geary for email client looks and functions very well in the RC2 Gnome build. Awesome work guys. 

Not sure if I can ask here, How can I contribute for the project?

**Comment by agajews** [comment]
We can talk on the [gitter chat](https://gitter.im/Apricity-OS/apricity-build)

**Comment by dealloc** [comment]
I personally use Thunderbird since I require GPG support and I haven't found that in Geary yet
